### ISSUE TITLE
Capacitor values overlap into negativ

### ISSUE THREAD

**Issue by tigerdan2** [ArclightTW/Tiny-Reactors-OUTDATED#19]
tinyreactors-1.12-0.5.3 | testet in SP

Pretty straigt forward
combine Capacitator over and over and again , and at some point it will be negativ

http://prntscr.com/hq7qdg

possible Fixes
-replace any negativ value with maximum value
-store the limit/capacity  using long 
pretty sure you can store long in a NBTTagCompound

**Comment by ArclightTW** [comment]
Thanks for pointing this out. I will be sure to fix the maths for this in the newest version.

**Comment by ArclightTW** [comment]
Please review the new repository for new issues and tracking: https://github.com/ArclightTW/Tiny-Reactors
