### ISSUE TITLE
Breaking capacitor with pickaxe makes the capacitor unusalbe

### ISSUE THREAD

**Issue by darkphan** [ArclightTW/Tiny-Reactors-OUTDATED#20]
If you break a capacitor with a pickaxe and place the capacitor down again it can no longer store power. 

EDIT: Rotating the capacitor with the crescent hammer from Thermal Expansion also breaks the usability of the block

**Comment by ArclightTW** [comment]
Thanks for pointing this out. I will be sure to fix the maths for this in the newest version.

**Comment by VallenFrostweaver** [comment]
This is true with the Tiny Wrench. It turns into "Capacitor" with no stats in my inventory. Breaking one with a pick doesn't seem to have the effect for me that darkphan described. In either case the power stored inside is lost on breaking or shift clicking with the wrench to pick up.

**Comment by ArclightTW** [comment]
I’m working on a major overhaul of the mechanics at the moment for an upcoming release so will be sure to protect against all break conditions.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by VallenFrostweaver** [comment]
Sounds good. Let me know when it's set. I worked with Kashdeya a while back on this for bug checking and I'm still eager to get a video out on this mod.  Thanks.

**Comment by ArclightTW** [comment]
Thanks, I'm glad to hear you're still keen on covering the mod! I'm reimplementing from scratch, as stated above, and have just got onto "upgrade system" for the Capacitors and Energy Ports so will take extra care to ensure nothing breaks the mechanics.

**Comment by VallenFrostweaver** [comment]
I have to say it's shaped up to look really really nice and I look forward to your overhaul. I would recommend the volume gets toned down by default though as that may scare some people away (most don't want to touch configs in my experience).

**Comment by ArclightTW** [comment]
Please review the new repository for new issues and tracking: https://github.com/ArclightTW/Tiny-Reactors
