### ISSUE TITLE
[1.12.2 v.1.12-0.5.3] Reactor Controller visual glitch

### ISSUE THREAD

**Issue by VallenFrostweaver** [ArclightTW/Tiny-Reactors-OUTDATED#21]
As the reactor is being used the red bar at the top of the Reactor controller glitches through the face when looking at it from different angles. This is not in the GUI but in the world when looking at the reactor.

**Comment by ArclightTW** [comment]
Please review the new repository for new issues and tracking: https://github.com/ArclightTW/Tiny-Reactors
