### ISSUE TITLE
[1.12.2 v.1.12-0.5.3] Overlooked Config default

### ISSUE THREAD

**Issue by VallenFrostweaver** [ArclightTW/Tiny-Reactors-OUTDATED#22]
The Reactor Heat Scale in the configs is set at 1 and not 100 like the tool tip says. It takes weeks to get up to heat by default now. FYI

**Comment by ArclightTW** [comment]
Please review the new repository for new issues and tracking: https://github.com/ArclightTW/Tiny-Reactors
